### ISSUE TITLE
Keys containing dots are not correctly preserved

### ISSUE THREAD

**Issue by tomnomnom** [FGRibreau/gron#1]
As an example, these two commands provide identical output despite the input objects being different:

```
▶ echo '{"foo.bar": 123}' | gron.js | ungron.js
{
  "foo": {
    "bar": 123
  }
}
```

```
▶ echo '{"foo": {"bar": 123}}' | gron.js | ungron.js
{
  "foo": {
    "bar": 123
  }
}
```

**Comment by FGRibreau** [comment]
It took me two minutes to fix this (fixed in v.3.0.1), thanks for the report :)

**Comment by tomnomnom** [comment]
Ah, sadly it looks like this has introduced another bug; keys containing `__*__` are now converted to `.`.

E.g.

```
▶ echo '{"foo__*__bar": 123}' | gron.js 
json = {};
json["foo.bar"] = 123;
```

**Comment by FGRibreau** [comment]
I don't use sentinel anymore in v4, it fixes every corner case like this with way less code :)
