### ISSUE TITLE
Keys containing invalid chars are left bare rather than quoted

### ISSUE THREAD

**Issue by tomnomnom** [FGRibreau/gron#2]
For example, in this command:

```
▶ curl -s http://headers.jsontest.com/ | gron.js
json = {};
json.X-Cloud-Trace-Context = "3caf60ff9302c0a9f41636817049cd5e/7175341988887701355";
json.Host = "headers.jsontest.com";
json.User-Agent = "curl/7.43.0";
json.Accept = "*/*";
```

`json.X-Cloud-Trace-Context = "3caf60ff9302c0a9f41636817049cd5e/7175341988887701355";` is not valid JavaScript

**Comment by FGRibreau** [comment]
Fixed, I did it quite fast yesterday night and refactored it this morning. No more sentinel and invalid key names are supported :+1:
