### ISSUE TITLE
Gron operation crashes on large JSON files

### ISSUE THREAD

**Issue by tomnomnom** [FGRibreau/gron#3]
While looking at performance I've found that gron crashes when the JSON input is quite large.

E.g:

```
▶ time cat 22mb.json | gron.js > /dev/null
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x109838c [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewInternalizedStringImpl(v8::internal::Handle<v8::internal::String>, int, unsigned int) [node]
 6: v8::internal::StringTable::LookupString(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>) [node]
 7: v8::internal::JSReceiver::HasProperty(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::Name>) [node]
 8: v8::internal::Runtime_HasProperty(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 9: 0x347ddd2092a7
Aborted (core dumped)

real    1m16.576s
user    1m24.516s
sys 0m0.540s
```

The JSON file in question was produced by this python script:

``` python
import json
d = {"a": "a", "b": "b", "c": "c"}
dd = [d]*700000
print json.dumps({"data": dd})
```

**Comment by FGRibreau** [comment]
Haha, indeed, it could use a stream approach to read input!

That could be a great improvement but then who handle json files with 700 000 entries **daily**?  

It seems like premature optimization, I will wait for more feature requests before doing anything because currently gron works in most case and does the job pretty well (regarding its number of line of codes :))

**Comment by penpendede** [comment]
I work at a GIS company and I can tell you that frequent handling of huge JSON files is not at all rare. There are tons of geographical information that is provided as JSON files that tend to be huge. While the majority of these are rarely updated there is still a large number of them which is updated on a daily basis (or even more frequently).

**Comment by FGRibreau** [comment]
@penpendede I perfectly understand but as I said before then gron is not for you :)

**Comment by tomnomnom** [comment]
@penpendede shameless self promotion, but it seems reasonable in this situation to suggest trying the original version of gron: https://github.com/tomnomnom/gron

It has no runtime dependencies and handles big files pretty well :)

**Comment by FGRibreau** [comment]
Indeed @tomnomnom, I forgot to cite your version but I should have!

I'm closing this issue as I have been pretty clear here about the wanted scope of gron :)
